### ISSUE TITLE
Did this project have any results? 

### ISSUE THREAD

**Issue by zqs01** [xingchensong/Speech-Transformer-tf2.0#1]
Did this project have any results?  thank you.

**Comment by xingchensong** [comment]
Currently, no.  This project can overfit small dataset(containing 10 audios) which means transformer has been correctly built, but to get a good result in whole librispeech corpus , u need to finetune hyperparams which is not timeworthy for me.  I have other things to do, maybe i can keep on testing transformer after i finish them.

**Comment by zqs01** [comment]
OK，thank you!
