### ISSUE TITLE
where is the train-clean-100-debug.scp

### ISSUE THREAD

**Issue by w5688414** [xingchensong/Speech-Transformer-tf2.0#2]
> ileNotFoundError: [Errno 2] No such file or directory: '/home/.../data/LibriSpeech/librispeech/data/train-clean-100-debug.scp'

I got an error, can you show me where is the scp, or show me how to generate it

**Comment by xingchensong** [comment]
see [train-clean-100-debug.scp](https://github.com/xingchensong/Speech-Transformer-tf2.0/blob/master/datasets/librispeech/data/train-clean-100-debug.scp) and [make_scp.py](https://github.com/xingchensong/Speech-Transformer-tf2.0/blob/master/datasets/librispeech/make_scp.py#L1)
